"""Regression corpus for the 2026-10 classifier vocabulary pass: global-hiring wording that must NOT be rejected, and restriction
wording (English + es/fr/pt/de/it/nl, explicit on-site, passport / state-resident / entity gates) that must be."""
import os, sys
for _k in ("SUPABASE_URL", "SUPABASE_KEY", "CEREBRAS_API_KEY", "GROQ_API_KEY", "OPENAI_API_KEY", "ANTHROPIC_API_KEY"):
    os.environ.setdefault(_k, "x")
import logging
logging.disable(logging.CRITICAL)
import classifier as C

BASE = "You will own onboarding, adoption and renewals for our customers and partner closely with sales and product. " * 3


def run(loc, desc, wt="Remote"):
    return C._keyword_classify_location_detail({"title": "Customer Success Manager", "location": loc, "country": "", "description_snippet": desc,
                                                "workplace_type": wt, "source_ats": "X", "role_category": "CS"})[0]


LOC_KEEP = [
    'Remote - Worldwide',
    'Worldwide',
    'Anywhere',
    'Remote (Global)',
    'Global',
    'Remote, Anywhere',
    'Work from anywhere',
    'Remote - Anywhere in the world',
    'Fully Remote - Global',
    'Remote | Worldwide',
    'Global Remote',
    'Remote (Worldwide)',
    'International (Remote)',
    'Distributed',
    'Remote – Any location',
    'Remote - All countries',
    'Remote, Earth',
    'Remote - Global (any timezone)',
    '🌍 Remote',
    '🌎 Anywhere',
    'Remote, EMEA',
    'EMEA',
    'Remote - Africa',
    'Africa',
    'Remote (EMEA)',
    'Europe/Middle East/Africa',
    'Remote Africa and Europe',
    'Remote, Worldwide (Any Timezone)',
    'Anywhere (Remote)',
    'Location independent',
    'Remote - Multiple Countries',
    'Remote - International',
    'Remote (Any Country)',
    '100% Remote - Worldwide',
    'Telecommute - Worldwide',
    'Virtual - Global',
    'Remote - Global (EOR)',
    'Remote – Worldwide (Contractor)',
    'Remote / Anywhere',
    'MEA',
    'Pan-Africa',
    'Pan-African',
    'Sub-Saharan Africa',
    'East Africa',
    'West Africa',
    'Southern Africa',
    'North Africa',
    'Northern Africa',
    'Central Africa',
    'Remote - Africa & Middle East',
    'Remote, Africa/Europe',
    'EMEA Remote',
    'Remote – EMEA',
    'Remote (EMEA/APAC)',
    'AMER, EMEA',
    'Remote - Nigeria, Ghana, Kenya',
    'Nigeria, Kenya, South Africa',
    'Remote - Anglophone Africa',
    'Africa (Remote)',
    'Remote Africa',
    'Remote - Middle East & Africa',
    'Remote - EMEA & APAC',
    'EMEA/LATAM',
    'Remote - Americas, EMEA',
    'Remote – Africa, Europe and Middle East',
    'Africa and the Middle East',
    'Remote: Anywhere',
    'Remote Anywhere',
    'Remote (Anywhere)',
    'Anywhere, Remote',
    'Work From Home - Worldwide',
    'WFH Global',
    'Remote-Global',
    'Remote_Worldwide',
    'Remote worldwide',
    'remote - worldwide',
    'GLOBAL',
    'WORLDWIDE',
    'Remote | Global',
    'International',
    'Globally',
    'Remote — Global',
    'Remote – International',
    'Remote (International)',
    'Télétravail - Monde entier',
    'Remoto - Todo el mundo',
    'Weltweit remote',
    'Remoto (Global)',
    'Remoto - Mundo',
    'Remote Worldwide (Contractor/EOR)',
    'Worldwide (Remote-first)',
    'Remote - Global Talent',
    'Open to remote worldwide',
    'Remote, Planet Earth',
    'Anywhere in the World',
    'Anywhere in the world (remote)',
    'Remote — anywhere in the world',
    'Remote – Worldwide (excluding US)',
    'Global (ex-US)',
]
LOC_REJECT = [
    'Remote - US',
    'Remote (United States)',
    'United States',
    'Remote, USA',
    'Remote - Canada',
    'London, United Kingdom',
    'Remote - UK',
    'Remote, Germany',
    'Berlin',
    'New York, NY',
    'San Francisco, CA',
    'Remote - California',
    'Remote (Texas)',
    'Austin, TX (Hybrid)',
    'Remote - India',
    'Bangalore, India',
    'Remote, Australia',
    'Sydney',
    'Toronto, ON',
    'Remote - France',
    'Paris',
    'Remote – Brazil',
    'São Paulo',
    'Remote, Mexico',
    'Singapore',
    'Tokyo, Japan',
    'Remote - LATAM',
    'Remote - APAC',
    'Remote - North America',
    'Remote (Americas)',
    'Remote - US/Canada',
    'Remote - Eastern Time',
    'Remote, EST',
    'Remote - US East Coast',
    'Remote - PST',
    'Remote (US only)',
    'Remote - Colorado',
    'Remote, Florida',
    'Dublin, Ireland',
    'Remote - Ireland',
    'Amsterdam',
    'Remote - Netherlands',
    'Remote - Spain',
    'Madrid',
    'Remote - Poland',
    'Warsaw',
    'Remote - Philippines',
    'Manila',
    'Remote - Argentina',
]
DESC_KEEP = [
    'We hire in over 50 countries and you can work from anywhere in the world.',
    'This position is open to candidates worldwide with no location restrictions.',
    "We are a remote-first company; you can be based anywhere as long as you overlap with our team's working hours.",
    'Work from anywhere. We have no offices and employees in 40 countries.',
    'We are location independent and hire globally through our employer of record partner.',
    'You can live anywhere in the world that has reliable internet.',
    'This role is fully remote and open to applicants in any country or timezone.',
    'Our headquarters are in San Francisco, but the team is distributed across the globe and this role can be done from anywhere.',
    'US citizenship is not required for this role.',
    'We do not require you to be located in any particular country.',
    'Candidates from all over the world are welcome to apply.',
    "We welcome applications from anywhere; we'll support you with an EOR or contractor agreement.",
    'Remote across EMEA with occasional team offsites a couple of times a year.',
    'Our team is 100% remote and spans 25 time zones.',
    'Fully distributed company. You choose where you work.',
    'Based anywhere in Africa or Europe, working a European time zone.',
    'Open to anyone, anywhere. We are timezone flexible.',
    'Travel to our annual company retreat is expected once a year.',
    'This is a global role; location is not a factor in hiring decisions.',
    'We hire talent wherever it lives. Fully remote, async-first.',
    'Applicants from any country can apply; relocation is not required.',
    'No visa sponsorship is necessary because you work remotely from your home country.',
    'Remote-first. Pick a coworking space or work from home, anywhere you like.',
    'Our company is registered in the UK but we hire remote employees across the world.',
    'Eligible candidates can be located in any country where we operate or via our EOR in 100+ countries.',
    'Fully remote position – work from your home country, we hire in Africa, Europe and the Middle East.',
    'Trabajo remoto desde cualquier lugar del mundo.',
    'Poste en télétravail complet, ouvert aux candidats du monde entier.',
    'Vollständig remote, Sie können von überall auf der Welt arbeiten.',
    'Trabalho 100% remoto, de qualquer lugar do mundo.',
    'We offer visa sponsorship for relocating candidates, but this particular role can be done remotely from anywhere.',
    'No relocation is required.',
    'We do not discriminate on the basis of nationality or citizenship status.',
    'You do not need to be a US citizen to apply.',
    'There is no requirement to be located in the United States.',
    "Our customers are mostly based in the US and Canada, so you'll support North American accounts, working from wherever you are.",
    "You'll work with customers across the UK, Germany and France from your home office anywhere in the world.",
    'Our offices are in London and New York, but this role is remote and open globally.',
    'Occasional travel (up to 10%) may be required.',
    'You will need a reliable internet connection and a quiet workspace at home.',
    'Hiring in: Africa, Europe, Middle East. Fully remote.',
    'We are able to employ people in most countries through Deel.',
    'The team is spread across Lagos, Nairobi, Cape Town, London and Berlin and works fully remotely.',
    'Remote role. Candidates in any location are welcome, subject to our ability to employ in your country.',
    'This is a fully remote role and can be performed from any country in which we have a legal entity or via an EOR.',
    'We are open to remote candidates in EMEA time zones.',
    'Looking for someone in EMEA to join our remote team.',
    'Work remotely from any African country.',
    'Contractor position: you can be based in any country.',
    'Remote (international candidates welcome).',
    'International applicants encouraged. English fluency required.',
    'You must be fluent in English and French.',
    'Must have a strong understanding of US tax law.',
    'Experience selling into the US market is a plus.',
    'You will be working US business hours (overlap with 4 hours of EST) from anywhere.',
    'Willing to work flexible hours to support customers in different time zones.',
    'Residents of any country may apply.',
    'Our compensation is location-agnostic: the same pay wherever you live.',
    'We pay a global salary band regardless of where you live.',
    'Citizens of any nationality may apply.',
    'Right to work: we will help you get set up as a contractor in your country of residence.',
    'Not limited to a specific country or region.',
    'Candidates from Africa are strongly encouraged to apply.',
    'We have no preference on location, as long as you can work during our core hours (10am-2pm UTC).',
    'Based anywhere between UTC-1 and UTC+4.',
    'We support customers who run hybrid and on-site operations.',
    'Our product helps teams manage in-person events and hybrid meetings.',
    "You'll host in-person customer workshops a few times a year.",
    'Experience with on-site implementation at customers is a plus.',
    'Trabajamos 100% remoto y puedes residir en cualquier país.',
    'No es necesario residir en España.',
    'Sin necesidad de vivir en Madrid; trabaja desde donde quieras.',
    'Não é necessário morar em Portugal, o trabalho é remoto.',
    'Ein Wohnsitz in Deutschland ist nicht erforderlich.',
    'Pas besoin de résider en France, télétravail complet.',
    'Non è necessario risiedere in Italia.',
    'Je hoeft niet in Nederland te wonen.',
    'You must hold a valid passport for occasional travel.',
    'The office in Madrid is optional; most of us work remotely.',
    'This is not a remote-only company culture problem; we are remote-first and fully remote.',
    'Our customers use hybrid work models and on-site kiosks.',
    'We are a fully remote company with no offices; in-person meetups are optional.',
    'Remote work is available and encouraged for this role.',
    'Attendance at our annual in-person summit is expected once a year.',
    'Los clientes se encuentran en España, pero el equipo trabaja de forma remota desde cualquier lugar.',
    'Hybrid cloud experience is required.',
    'You should be comfortable with on-site customer visits when needed.',
]
DESC_REJECT = [
    'Candidates must reside in the United States.',
    'This role requires you to be located in Germany.',
    'You must be authorized to work in the UK without sponsorship.',
    'US work authorization required; we are unable to sponsor visas.',
    'This position is hybrid, with three days a week in our London office.',
    'Onsite role. You will be expected in the office five days a week.',
    'Must be able to work from our Austin office.',
    'Only candidates based in Canada will be considered.',
    'Applicants must be eligible to work in Australia.',
    'This role is restricted to residents of the EU.',
    'You must have the right to work in Ireland.',
    'Active Secret security clearance required.',
    'U.S. citizens only due to government contract requirements.',
    'Must be a US citizen or permanent resident.',
    'Remote, but you must be located in the Eastern Time zone in the United States.',
    'Remote within the US only.',
    'We are only hiring in the following states: CA, NY, TX, WA.',
    'This is a remote position open to residents of Brazil only.',
    'Relocation to Singapore is required.',
    'Candidates must live within commuting distance of our Chicago office.',
    'Position based in Toronto; relocation assistance available. Must be in the office.',
    'Residency in India is mandatory for this role.',
    'Due to local regulations we can only hire in Poland.',
    'Must have a valid work permit for Canada.',
    'We can only consider applicants currently residing in Mexico.',
    'Eligibility to work in the United States is required; no sponsorship available.',
    'Los candidatos deben residir en España.',
    'Les candidats doivent résider en France.',
    'Bewerber müssen in Deutschland wohnhaft sein.',
    'Candidatos devem residir no Brasil.',
    'You must be based in the UK to be considered; this is not a remote-anywhere role.',
    'In-person presence at our Dubai headquarters is required.',
    'This role is only open to people living in Australia or New Zealand.',
    'Applicants must be legally authorised to work in the Netherlands.',
    'Must be able to commute to our Lagos office three days a week.',
    'You must be physically present in the office at least four days a week.',
    'In-office role: employees are required on site daily.',
    'In-person presence at our Dubai headquarters is required.',
    'You will be required to work from our Lagos office.',
    'This is not a remote position.',
    'Remote work is not available for this role.',
    'Position is 100% on-site at the customer location.',
    'Hybrid schedule: Tuesday-Thursday in the office.',
    'We require employees to be within 50 miles of our Denver office.',
    'Must live in the Bay Area.',
    'Applicants must hold a UK passport or settled status.',
    'Only EU citizens or those with EU work authorization may apply.',
    'Candidates must be eligible to work in the US on a full-time basis without sponsorship now or in the future.',
    'We cannot sponsor work visas; you must already have the right to work in Canada.',
    'Must be a resident of Texas, Florida, or Georgia.',
    'TS/SCI clearance required.',
    'Must be able to obtain and maintain a public trust clearance.',
    'Only considering candidates in Pacific Time.',
    'Candidates must be located within the Central European Time zone, in Germany.',
    'Open only to residents of South Africa.',
    'This role is for Nigerian residents only.',
    'Residency in the Philippines is required.',
    'Preference will be given to candidates in the United States who can work EST hours; candidates outside the US will not be considered.',
    'Los candidatos deben residir en España.',
    'Se requiere residir en México.',
    'Debes vivir en Colombia para aplicar a esta vacante.',
    'Les candidats doivent résider en France.',
    'Vous devez habiter en Belgique.',
    'Résidence en France obligatoire.',
    'Candidatos devem residir no Brasil.',
    'É necessário morar em Portugal.',
    'Bewerber müssen in Deutschland wohnhaft sein.',
    'Wohnsitz in Deutschland erforderlich.',
    'Sie müssen in Österreich leben.',
    'Devi risiedere in Italia.',
    'Residenza in Italia obbligatoria.',
    'Je moet in Nederland wonen.',
    'Autorisation de travailler en France requise.',
    'Se requiere autorización para trabajar en España.',
    'Arbeitserlaubnis für Deutschland erforderlich.',
    'Presencia en la oficina de Madrid obligatoria tres días por semana.',
    'Présence au bureau de Paris obligatoire deux jours par semaine.',
    'Präsenz im Büro in München erforderlich.',
    'Presença no escritório em São Paulo obrigatória.',
    'Applicants must have a US passport.',
    'Only considering candidates in Pacific Time.',
    'This role is on-site only.',
    'This is not a remote role.',
    'Je moet in Nederland wonen.',
    'Debes residir en Argentina.',
    'Müssen in der Schweiz leben.',
]

fails, n = [], 0
for l in LOC_KEEP:
    n += 1
    if run(l, BASE) == "no_match":
        fails.append(f"false reject, location {l!r}")
for l in LOC_REJECT:
    n += 1
    if run(l, BASE, wt="") != "no_match":
        fails.append(f"false accept, location {l!r}")
for d in DESC_KEEP:
    for loc in ("Remote - Worldwide", ""):
        n += 1
        if run(loc, BASE + d) == "no_match":
            fails.append(f"false reject ({loc or 'blank location'}): {d}")
for d in DESC_REJECT:
    for loc in ("Remote - Worldwide", ""):
        n += 1
        if run(loc, BASE + d) != "no_match":
            fails.append(f"false accept ({loc or 'blank location'}): {d}")
# a time-zone range that spans every inhabited zone is no restriction; a single zone is
for l, ok in (("Remote (time zones UTC-10 to UTC+14 only)", True), ("Remote (UTC-12 to UTC+14)", True), ("Remote (time zones UTC-4 to UTC-4 only)", False)):
    n += 1
    if (run(l, BASE) == "match") != ok:
        fails.append(f"time-zone range {l!r}")
# a privacy-notice sentence naming a state is not an eligibility rule; a real rule next to it still is
n += 2
if run("Remote - Worldwide", BASE + " Pursuant to the California Consumer Privacy Act, this notice explains our practices for job applicants residing in California.") == "no_match":
    fails.append("CCPA notice must not reject")
if run("Remote - Worldwide", BASE + " Privacy notice. You must be a California resident to apply.") != "no_match":
    fails.append("a real state-residency rule beside a privacy notice must reject")
print(f"classifier vocabulary checks: {n - len(fails)}/{n} passed")
for f in fails:
    print("  FAIL", f)
sys.exit(1 if fails else 0)
